In [44]:
import random

from numpy.ma.core import concatenate

#problem specifikation
values=[5, 10, 20, 15, 5, 6]
weights = [2, 5 , 10, 7, 20, 15]
capacity=30


In [45]:
#data representation
import random
chromosone = [random.randint(0,1) for _ in range(len(values))]
print(chromosone)

[1, 0, 0, 1, 1, 1]


In [46]:
#initsialise specifikation
import numpy as np
n_init= 20
pop_init=np.array( [[random.randint(0,1) for _ in range(len(values))] for _ in range(n_init)])
#pop_init_2=[chromosone for _ in range(n_init) for chromosone in [random.randint(0,1) for _ in range(len(values))]]
print(pop_init)


[[0 1 1 1 0 0]
 [0 0 0 0 1 1]
 [0 0 1 0 1 0]
 [1 1 1 1 0 1]
 [1 0 0 1 0 0]
 [0 0 1 1 1 0]
 [0 0 1 1 1 1]
 [0 1 0 0 1 0]
 [0 0 0 0 1 0]
 [1 1 1 0 1 0]
 [1 1 0 0 0 1]
 [0 1 0 1 0 0]
 [0 0 0 0 1 0]
 [1 0 0 1 0 0]
 [0 1 1 0 0 0]
 [1 0 1 1 0 0]
 [1 1 1 1 0 1]
 [1 1 1 1 0 1]
 [1 1 1 0 1 0]
 [0 0 1 1 1 0]]


In [47]:
#calculate fitness
values_all =pop_init*values
values_sum = values_all.sum(axis=1, keepdims=True)
print(values_sum )

[[45]
 [11]
 [25]
 [56]
 [20]
 [40]
 [46]
 [15]
 [ 5]
 [40]
 [21]
 [25]
 [ 5]
 [20]
 [30]
 [40]
 [56]
 [56]
 [40]
 [40]]


In [48]:
weights_all= pop_init * weights
weights_sum = weights_all.sum(axis=1, keepdims=True)
print(weights_sum)

[[22]
 [35]
 [30]
 [39]
 [ 9]
 [37]
 [52]
 [25]
 [20]
 [37]
 [22]
 [12]
 [20]
 [ 9]
 [15]
 [19]
 [39]
 [39]
 [37]
 [37]]


In [49]:
#fitness
fitness =np.where(weights_sum>capacity, 0, values_sum)
print(fitness)


[[45]
 [ 0]
 [25]
 [ 0]
 [20]
 [ 0]
 [ 0]
 [15]
 [ 5]
 [ 0]
 [21]
 [25]
 [ 5]
 [20]
 [30]
 [40]
 [ 0]
 [ 0]
 [ 0]
 [ 0]]


In [50]:

def cross_over(p1,p2):
    i=random.randint(0,len(p1))
    os_1=p1[:i]+p2[i:]
    os_2=p2[:i]+p1[i:]
    return os_1,os_2

os_1,os_2=cross_over([1, 1, 1, 1, 1, 0], [0, 0, 0, 1, 1 ,1])
print(os_1, os_2)


[0, 0, 0, 1, 1, 1] [1, 1, 1, 1, 1, 0]


In [52]:
m_rate=0.1
def mutate(os_1, os_2, m_rate):
    mutation_probability = [random.random() for _ in range(len(os_1))]
    os_1_m = [1-b if p<m_rate else b for p,b in zip(mutation_probability, os_1)]
    os_2_m = [1-b if p<m_rate else b for p,b in zip(mutation_probability, os_2)]
    return os_1_m, os_2_m
os_1_m, os_2_m=mutate([1, 1, 1, 1, 1, 0], [0, 0, 0, 1, 1 ,1],m_rate)
print(os_1_m, os_2_m)


[1, 1, 0, 1, 1, 0] [0, 0, 1, 1, 1, 1]


In [53]:
import pandas as pd
pop_init_df= pd.DataFrame({'population':list(pop_init), 'fitness':fitness.ravel()})
print(pop_init_df)

            population  fitness
0   [0, 1, 1, 1, 0, 0]       45
1   [0, 0, 0, 0, 1, 1]        0
2   [0, 0, 1, 0, 1, 0]       25
3   [1, 1, 1, 1, 0, 1]        0
4   [1, 0, 0, 1, 0, 0]       20
5   [0, 0, 1, 1, 1, 0]        0
6   [0, 0, 1, 1, 1, 1]        0
7   [0, 1, 0, 0, 1, 0]       15
8   [0, 0, 0, 0, 1, 0]        5
9   [1, 1, 1, 0, 1, 0]        0
10  [1, 1, 0, 0, 0, 1]       21
11  [0, 1, 0, 1, 0, 0]       25
12  [0, 0, 0, 0, 1, 0]        5
13  [1, 0, 0, 1, 0, 0]       20
14  [0, 1, 1, 0, 0, 0]       30
15  [1, 0, 1, 1, 0, 0]       40
16  [1, 1, 1, 1, 0, 1]        0
17  [1, 1, 1, 1, 0, 1]        0
18  [1, 1, 1, 0, 1, 0]        0
19  [0, 0, 1, 1, 1, 0]        0


In [56]:
#cost function, cross over
def fittness_calculation(p1, p2, values, weights, capacity):
      # ---- Parent 1 ----
    total_value_p1 = np.dot(p1, values)
    total_weight_p1 = np.dot(p1, weights)

    if total_weight_p1 <= capacity:
        fitness_p1 = total_value_p1
    else:
        fitness_p1 = 0

    # ---- Parent 2 ----
    total_value_p2 = np.dot(p2, values)
    total_weight_p2 = np.dot(p2, weights)

    if total_weight_p2 <= capacity:
        fitness_p2 = total_value_p2
    else:
        fitness_p2 = 0

    return fitness_p1, fitness_p2

