In [ ]:
#steg 1: importera numpy och ladda data

import numpy as np
#print("Numpy fungerar!")

#ladda data

data = np.load("credit_score_fairness_data.npy")
print(data)

[[0. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]]


In [ ]:
#Steg 2: dela upp data i tre olika arrayer

protected_attribute = data[:, 0].astype(int)
true_credit_worthiness = data[:, 1].astype(int)
algorithm_prediction = data[:, 2].astype(int)

print(protected_attribute)
print(true_credit_worthiness)
print(algorithm_prediction)


[0 1 1 ... 1 0 0]
[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]


In [ ]:
#steg 3:Calculate equal opportunity and equalized error rates by calculating the elements of a confusion matrix. Does the algorithm predict credit scores fairly?
#För att beräkna equal opportunity och equalized error rates behöver vi först skapa en confusion matrix för varje grupp (de som tillhör den skyddade gruppen och de som inte gör det).

#"bra credit score" = 1, "dålig credit score" = 0
#TP=true positive, FP=false positive, TN=true negative, FN=false negative

def confusion_matrix(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    return TP, FP, TN, FN

#om division med noll sker, returnera 0 istället för att ge ett fel
def safe_division(n, d):
    return n / d if d != 0 else np.nan

#beräkna rates för grupperna
