In [11]:
#Write a python code that solves the following Knapsack1 problem. Make sure your implementation allows 
#for more than one selection of each item as a solution. Evolva algortima (EA) is a good choice for this problem.

#steg 1: Data representation
capacity = 15
weights= [1, 1, 2, 4, 12]
values = [1, 2, 2, 10, 4]

#max antal av varje item som kan väljas
max_count=[capacity//w for w in weights]

n_init=50



In [12]:
# steg 2: skapar individer och population
import random
import numpy as np

#skapa population med slumpmässiga antal av varje item, upp till max_count
pop_init= np.array([[random.randint(0, max_count[i]) for i in range(len(values))] for _ in range(n_init)])

# def initialize_population(pop_size):
#     population = []
#     for _ in range(pop_size):
#         individual = [random.randint(0, max_count[i]) for i in range(len(values))]
#         population.append(individual)
#     return population

print(pop_init)

[[14  3  6  2  0]
 [12  9  0  0  1]
 [15 11  6  2  0]
 [13  3  6  2  0]
 [10 12  4  2  0]
 [ 9  3  5  2  0]
 [ 1  0  4  2  1]
 [ 4 10  4  2  1]
 [11 15  2  1  0]
 [10  0  0  1  1]
 [10  3  5  3  1]
 [ 5  9  7  1  1]
 [ 2  8  7  1  1]
 [14 14  3  1  0]
 [15  3  6  2  0]
 [11  3  3  2  0]
 [ 3  1  5  0  0]
 [ 2  4  7  1  1]
 [14  9  4  2  0]
 [ 2  4  6  2  0]
 [ 4 11  6  2  1]
 [ 8  1  0  0  0]
 [ 4  0  3  2  1]
 [ 7  6  1  2  0]
 [ 5  6  6  3  0]
 [14  3  2  2  1]
 [14 13  6  2  1]
 [13  0  4  3  1]
 [13  5  6  2  0]
 [13  6  4  1  1]
 [ 0 12  4  1  0]
 [ 4 12  4  0  0]
 [ 3  1  6  2  1]
 [ 0  6  4  1  0]
 [ 0 12  0  0  1]
 [ 0 12  7  2  1]
 [ 6  8  7  2  1]
 [ 4 15  7  2  0]
 [15 11  6  3  0]
 [ 6  6  1  3  1]
 [ 7  2  1  3  1]
 [ 4 13  6  2  1]
 [ 9  1  0  1  0]
 [ 9 14  0  2  0]
 [ 9 15  3  3  1]
 [ 9 12  2  3  1]
 [ 8  8  7  3  0]
 [ 9  1  5  2  1]
 [14  9  2  2  0]
 [14 10  1  2  0]]


In [ ]:
# steg 3: fitnessfunktion, beräknar värdet av en individ
def fitness(population):
    w_sum= (population * weights).sum(axis=1)
    v_sum= (population * values).sum(axis=1)
    # straffa individer som överskrider kapaciteten
    penalty = np.where(w_sum > capacity, 0, v_sum)
    return penalty


In [ ]:
# steg 4: selektion, väljer individer baserat på fitness

def selection(population):
   contestaants = random.sample(population, 3)
   return max(contestaants, key=fitness)

In [10]:
#steg 5: crossover, kombinerar två föräldrar för att skapa avkomma
def crossover(parent1, parent2):
    i = random.randint(1, len(parent1) - 1)
    child1 = parent1[:i] + parent2[i:]
    child2 = parent2[:i] + parent1[i:]
    return child1, child2

In [ ]:
#steg 6: mutation, introducerar variation i avkomman

def mutate(individual, mutation_rate=0.1):
    for i in range(len(individual)):
        if random.random() < mutation_rate:
            individual[i] = random.randint(0, max_count[i])
    return individual

In [ ]:
#main loop, EA implementation

