In [29]:
#Write a python code that solves the following Knapsack1 problem. Make sure your implementation allows 
#for more than one selection of each item as a solution. Evolva algortima (EA) is a good choice for this problem.
import random
#steg 1: Data representation
capacity = 15
weights= [1, 1, 2, 4, 12]
values = [1, 2, 2, 10, 4]

#max antal av varje item som kan väljas
max_count=[capacity//w for w in weights]

n_init=50
# --- Parametrar ---
N_population = 50
N_generations = 100
mutation_rate = 0.1

def create_individual():
    return [random.randint(0, max_count[i]) for i in range(len(values))]




In [30]:
# steg 2: skapar individer och population

import numpy as np

#skapa population med slumpmässiga antal av varje item, upp till max_count
pop_init= np.array([[random.randint(0, max_count[i]) for i in range(len(values))] for _ in range(n_init)])

# def initialize_population(pop_size):
#     population = []
#     for _ in range(pop_size):
#         individual = [random.randint(0, max_count[i]) for i in range(len(values))]
#         population.append(individual)
#     return population

print(pop_init)

[[ 2  1  1  1  0]
 [ 4 10  0  1  1]
 [15  6  0  3  1]
 [ 4  0  1  2  0]
 [ 1  9  6  3  0]
 [12 11  5  0  0]
 [ 6  6  3  1  0]
 [13  5  0  1  1]
 [13  8  2  2  0]
 [ 7  8  1  0  0]
 [ 8 12  2  1  1]
 [ 7  4  5  0  1]
 [15  2  1  3  0]
 [ 6 13  5  1  1]
 [ 7  0  1  0  1]
 [ 2  3  3  1  0]
 [ 8 10  4  2  1]
 [ 3  6  5  3  1]
 [10  5  2  0  0]
 [ 7 11  5  3  1]
 [12  9  7  2  0]
 [ 9  8  5  1  1]
 [ 0  2  4  2  1]
 [15 10  0  0  0]
 [ 4 14  2  2  1]
 [ 9  9  7  3  1]
 [ 6 10  6  2  1]
 [ 9 10  7  3  0]
 [ 3 13  5  3  0]
 [ 9 13  3  2  0]
 [ 5  8  4  2  0]
 [14 11  0  0  0]
 [ 0 11  1  0  1]
 [13  0  5  3  1]
 [13  5  5  3  1]
 [ 4  5  7  0  1]
 [ 3  1  6  1  0]
 [ 1  1  2  1  1]
 [ 2  9  0  1  1]
 [11  9  6  1  1]
 [11  9  5  2  1]
 [12  4  5  3  1]
 [15 10  1  1  1]
 [11  7  5  2  0]
 [ 3 10  4  1  1]
 [ 0 10  5  2  0]
 [ 7 11  0  1  0]
 [12  5  7  0  1]
 [11 11  1  0  0]
 [15  1  6  2  1]]


In [31]:
# steg 3: fitnessfunktion, beräknar värdet av en individ
def fitness(population):
    ind=np.array(population)
    w_sum= np.sum(ind * weights)
    v_sum= np.sum(ind * values)
    # straffa individer som överskrider kapaciteten
    if w_sum > capacity:
        return 0
    return v_sum
#printa svaren för kontroll


In [32]:
# steg 4: selektion, väljer individer baserat på fitness

def selection(population):
   selected= random.sample(population, 3)
   return max(selected, key=fitness)

In [33]:
#steg 5: crossover, kombinerar två föräldrar för att skapa avkomma
def crossover(parent1, parent2):
    i = random.randint(1, len(parent1) - 1)
    child1 = parent1[:i] + parent2[i:]
    child2 = parent2[:i] + parent1[i:]
    return child1, child2

In [34]:
#steg 6: mutation, introducerar variation i avkomman

def mutate(individual, mutation_rate=0.1):
    for i in range(len(individual)):
        if random.random() < mutation_rate:
            individual[i] = random.randint(0, max_count[i])
    return individual

In [35]:
# Evolutionary algorithm main loop:
population= [create_individual() for _ in range(N_population)]  # Skapa initial population

print("Startar evolutionär algoritm för knapsack problem...")

for generation in range(N_generations):
    #1. Utvärdera fitness
    population.sort(key=fitness, reverse=True)  # Sortera populationen efter fitness
    best_individual = population[0]
    best_fitness = fitness(best_individual)

    if generation % 10 == 0:
        print(f"Generation {generation}: Bästa värde = {best_fitness}, Vikt = {sum(np.array(population[0])*weights)}")

      # Skapa nästa generation
    next_generation = [best_individual] # Elitism: behåll den bästa individen

    while len(next_generation) < N_population:
        #välj två föräldrar baserat på fitness
        p1=selection(population)
        p2=selection(population)
        #skapa två avkommor genom crossover
        c1,c2=crossover(p1,p2)

        #mutera avkomman
        next_generation.append(mutate(c1))
        if len(next_generation) < N_population:
            next_generation.append(mutate(c2))
     
    population=next_generation # Begränsa populationen till N_population

    

Startar evolutionär algoritm för knapsack problem...
Generation 0: Bästa värde = 33, Vikt = 14
Generation 10: Bästa värde = 36, Vikt = 15
Generation 20: Bästa värde = 36, Vikt = 15
Generation 30: Bästa värde = 36, Vikt = 15
Generation 40: Bästa värde = 36, Vikt = 15
Generation 50: Bästa värde = 36, Vikt = 15
Generation 60: Bästa värde = 36, Vikt = 15
Generation 70: Bästa värde = 36, Vikt = 15
Generation 80: Bästa värde = 36, Vikt = 15
Generation 90: Bästa värde = 36, Vikt = 15


In [36]:
#slutresultat
population.sort(key=fitness, reverse=True)
best = population[0]
print("Bästa lösning:", best)
print("Bästa värde:", fitness(best))
print("Bästa vikt:", sum(np.array(best) * weights))

Bästa lösning: [0, 3, 0, 3, 0]
Bästa värde: 36
Bästa vikt: 15
