In [1]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
#from sklearn.datasets import make_regression    #för regression dataset


# ---------- 1) Load data ----------
data_path="Task_4_data.pkl"
with open(data_path, "rb") as file:
    df = pickle.load(file)  # brukar vara en pandas DataFrame

data = np.array(df,dtype=float)

# Last column = y
X= data[:, :-1]
y = data[:, -1]

In [3]:
m, n = X.shape
print(f"Dataset loaded: {m} samples, {n} features")
y=y.reshape(-1,1)  # gör y till en kolumnvektor

n_sampels=len(y)

# Lägg till bias/intercept (kolumn med 1:or)(m,1)
X_b= np.hstack((np.ones((m,1)), X))  # storlek (m,n+1)
print(X_b)

Dataset loaded: 2000 samples, 6 features
[[1.         0.63331217 0.66151928 ... 0.59095507 0.89914529 0.35492327]
 [1.         0.1745104  0.56793653 ... 0.54186994 0.02698504 0.39294494]
 [1.         0.41589021 0.30259215 ... 0.56635604 0.5104272  0.4532318 ]
 ...
 [1.         0.2661478  0.01743055 ... 0.84122622 0.11153334 0.48697425]
 [1.         0.16161665 0.05211133 ... 0.89657152 0.         0.4170532 ]
 [1.         0.73781773 0.9546661  ... 0.51944774 0.09011412 0.73387009]]
